# Generated by Django 5.0 on 2024-03-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
                ('picture', models.ImageField(default='', upload_to='picture/')),
                ('role', models.CharField(choices=[('buyer', 'buyer'), ('saler', 'saler')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Chiled', 'Chiled')], max_length=20, null=True)),
                ('size', models.CharField(choices=[('S', 'S'), ('L', 'L'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True)),
                ('brand', models.CharField(choices=[("Levi's", "Levi's"), ('Being Human', 'Being Human'), ('Biba', 'Biba'), ('Aurelia', 'Aurelia'), ('Max', 'Max')], max_length=20, null=True)),
                ('pname', models.CharField(max_length=20)),
                ('ppicture', models.ImageField(default='', upload_to='ppicture/')),
                ('disc', models.TextField()),
                ('pprice', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
