# Generated by Django 5.0 on 2024-03-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller')], max_length=20),
        ),
    ]
