# Generated by Django 5.0.4 on 2024-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_addcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='Quantity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='tprice',
            field=models.BigIntegerField(null=True),
        ),
    ]
